image: python:3.8-buster

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install pipenv==11.9.0
    - pipenv sync
    - pipenv run mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
    - public
  only:
    - master
