site_name: KYPO CRP
theme:
  name: material
  logo: 'img/kypo-simple.svg'
  favicon: 'img/kypo-simple.svg'
  

nav:
    - Home: index.md
    - Architecture: architecture.md
    - Installation:
        - Base infrastructure: 
            - Creation: installation/base-infrastructure/creation.md
            - Configuration: installation/base-infrastructure/configuration.md
        - KYPO Platform prerequisites: installation/kypo-platform-prerequisites.md
        - KYPO Platform configuration: installation/kypo-platform-configuration.md 
        - KYPO Platform deployment: installation/kypo-platform-deployment.md
    - KYPO Portal: 
        - Roles: kypo-portal/roles.md
        - Login & logout: kypo-portal/login-and-logout.md
        - Administration: kypo-portal/administration.md
        - Sandboxes: 
            - Sandbox Definition: kypo-portal/sandboxes/sandbox-definition.md
            - Pool: kypo-portal/sandboxes/pool.md
            - Resources: kypo-portal/sandboxes/resources.md
        - Trainings: 
            - Training Definition: kypo-portal/trainings/training-definition.md
            - Training Instance: kypo-portal/trainings/training-instance.md
            - Training Run: kypo-portal/trainings/training-run.md
    - Sandboxes: 
        - Sandbox Definition: sandboxes/sandbox-definition.md
        - Sandbox Topology: 
            - Topology Definition: sandboxes/sandbox-topology/topology-definition.md
            - Topology Instance: sandboxes/sandbox-topology/topology-instance.md
        - User Ansible: sandboxes/user-ansible.md
        - Sandbox SSH Access: sandboxes/sandbox-ssh-access.md   
    - API: 
        - Training service: api/training-swagger-open-api.md
        - User and Group service: api/user-and-group-swagger-open-api.md
        - Elasticsearch service: api/elasticsearch-swagger-open-api.md
        - Sandbox service: api/sandbox-service-swagger-open-api.md
    - License: license.md
    - Is it done yet?: is-it-done-yet.md
    - FAQ: faq.md
    - Extras:
        - Logging:
            - Architecture: extras/logging/architecture.md
            - How to use it: extras/logging/how-to-use-it.md 
        - Writing documentation - MkDocs: extras/writing-documentation-mkdocs.md
copyright: Copyright © 2020 Institute of Computer Science, Masaryk University

markdown_extensions:
    - admonition
    - sane_lists
    - smarty
    - toc:
        permalink: "#"
    - wikilinks
    - extra
    - nl2br
    - fenced_code
    - codehilite
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.superfences
extra_css: 
    - stylesheets/extra.css
