site_name: KYPO CRP
theme:
  name: material

nav:
    - Home: index.md
    - Architecture: architecture.md
    - Installation:
        - Base infrastructure: 
            - Creation: installation/base-infrastructure/creation.md
            - Configuration: installation/base-infrastructure/configuration.md
        - KYPO Platform prerequisites: installation/kypo-platform-prerequisites.md
        - KYPO Platform configuration: installation/kypo-platform-configuration.md 
        - KYPO Platform deployment: installation/kypo-platform-deployment.md
    - KYPO Portal: 
        - Roles: kypo-portal/roles.md
        - Login & logout: kypo-portal/login-and-logout.md
        - Administration: 
            - User: kypo-portal/administration/user.md
            - Group: kypo-portal/administration/group.md
            - Microservices: kypo-portal/administration/microservices.md
        - Sandboxes: 
            - Sandbox Definition: kypo-portal/sandboxes/sandbox-definition.md
            - Pool: kypo-portal/sandboxes/pool.md
        - Trainings: 
            - Training Definition: kypo-portal/trainings/training-definition.md
            - Training Instance: kypo-portal/trainings/training-instance.md
            - Training Run: kypo-portal/trainings/training-run.md
    - Sandboxes: 
        - Sandbox Topology: 
            - Topology Definition: sandboxes/sandbox-topology/topology-definition.md
            - Topology Instance: sandboxes/sandbox-topology/topology-instance.md
        - Sandbox Definition: sandboxes/sandbox-definition.md
        - Sandbox Manipulation Process: sandboxes/sandbox-manipulation-process.md
        - Sandbox SSH Access: sandboxes/sandbox-ssh-access.md   
    - API: 
        - Training service: api/training-swagger-open-api.yml
        - User and Group service: api/user-and-group-swagger-open-api.yml
        - Elasticsearch service: api/elasticsearch-swagger-open-api.yml
        - Sandbox service: api/sandbox-service-swagger-open-api.yml 
    - GDPR: gdpr.md
    - License: license.md
    - FAQ: faq.md
    - Extras:
        - Logging:
            - Architecture: extras/logging/architecture.md
            - How to use it: extras/logging/how-to-use-it.md 
        - Writing documentation - MkDocs: extras/writing-documentation-mkdocs.md
copyright: Copyright © 2020 Institute of Computer Science, Masaryk University

markdown_extensions:
    - admonition
    - sane_lists
    - smarty
    - toc:
        permalink: "#"
    - wikilinks
    - extra
    - nl2br
    - fenced_code
    - codehilite
extra_css: 
    - stylesheets/extra.css
