site_name: KYPO Cyber Range Platform
theme:
  name: material
  logo: 'img/kypo-simple.svg'
  favicon: 'img/kypo-simple.svg'



nav:
  - Home: index.md
  - Basic Concepts:
    - Use Cases: basic-concepts/use-cases.md
    - Terminology: basic-concepts/terminology.md
    - Conceptual Architecture: basic-concepts/conceptual-architecture.md
    - Typical Workflow: basic-concepts/typical-workflow.md
  - User Guide (Basic):
      - Overview: user-guide-basic/overview.md
      - Login & Logout: user-guide-basic/login-and-logout.md
      - Sandbox Agenda:
          - Overview: user-guide-basic/sandbox-agenda/sandbox-agenda-overview.md
          - Sandbox Definition: user-guide-basic/sandbox-agenda/sandbox-definition.md
          - Pool: user-guide-basic/sandbox-agenda/pool.md
          - Resources: user-guide-basic/sandbox-agenda/resources.md
      - Training Agenda:
          - Overview: user-guide-basic/training-agenda/training-agenda-overview.md
          - Training Definition: user-guide-basic/training-agenda/training-definition.md
          - Training Instance: user-guide-basic/training-agenda/training-instance.md
          - Training Run: user-guide-basic/training-agenda/training-run.md
      - Administration Agenda:
          - Overview: user-guide-basic/administration-agenda/administration-agenda-overview.md
          - Users: user-guide-basic/administration-agenda/users.md
          - Groups: user-guide-basic/administration-agenda/groups.md
          - Microservices: user-guide-basic/administration-agenda/microservices.md
  - User Guide (Advanced):
      - Overview: user-guide-advanced/user-guide-advanced-overview.md
      - Sandboxes:
          - Overview: user-guide-advanced/sandboxes/sandboxes-overview.md
          - Sandbox Definition: user-guide-advanced/sandboxes/sandbox-definition.md
          - Sandbox Topology:
              - Topology Definition: user-guide-advanced/sandboxes/sandbox-topology/topology-definition.md
              - Topology Instance: user-guide-advanced/sandboxes/sandbox-topology/topology-instance.md
          - Sandbox Provisioning: user-guide-advanced/sandboxes/sandbox-provisioning.md
          - Sandbox SSH Access: user-guide-advanced/sandboxes/sandbox-ssh-access.md
      - Trainings:
          - Overview: user-guide-advanced/trainings/trainings-overview.md
      - Users and Groups:
          - Overview: user-guide-advanced/users-and-groups/users-and-groups-overview.md
          - Roles: user-guide-advanced/users-and-groups/roles.md
  - Installation Guide:
      - Overview: installation-guide/installation-guide-overview.md
      - Base Infrastructure: installation-guide/base-infrastructure.md
      - KYPO Platform Prerequisites: installation-guide/kypo-platform-prerequisites.md
      - KYPO Platform Configuration: installation-guide/kypo-platform-configuration.md
      - KYPO Platform Deployment: installation-guide/kypo-platform-deployment.md
      - Setting up OIDC Provider: installation-guide/setting-up-oidc-provider.md
      - Platform Components: installation-guide/platform-components.md
  - Available Features: available-features.md
  - FAQ: faq.md
  - Reference:
      - Sandbox Service: reference/sandbox-service-swagger-open-api.md
      - Training Service: reference/training-swagger-open-api.md
      - User and Group Service: reference/user-and-group-swagger-open-api.md
      - Elasticsearch Service: reference/elasticsearch-swagger-open-api.md
      - Tables of Permissions: reference/tables-of-permissions.md
  - Extras:
      - Logging:
          - Architecture: extras/logging/architecture.md
          - How to Use It: extras/logging/how-to-use-it.md
      - Writing Documentation - MkDocs: extras/writing-documentation-mkdocs.md
  - Report Bugs: report-bugs.md
  - Authors: authors.md
  - Acknowledgements: acknowledgements.md
  - License: license.md
copyright: Copyright © 2020 KYPO CRP Team, Masaryk University

markdown_extensions:
  - admonition
  - sane_lists
  - smarty
  - toc:
      permalink: "#"
  - wikilinks
  - extra
  - nl2br
  - fenced_code
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
