name: Deploy docs CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.12"

      - name: Sync dependencies
        run: uv sync

      - name: Build MkDocs site
        run: uv run mkdocs build --strict --verbose --site-dir public

      - name: Upload Docs files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  upload_docs:
    needs: deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
